config/routes.rb
Rails.application.routes.draw do
resources :articles
root to: 'articles#index'
resources :articles do
  resources :comments
  end
  resources :tags

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
  #has_attached_file :image
  #validates_attachment_content_type
  has_attached_file :image, default_url: "/images/:style/missing.png", styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end

  def tag_list
    self.tags.collect do |tag|
    tag.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :articles, through: :taggings

  def to_s
   name
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
include ArticlesHelper

  def index
    @articles = Article.all
  end
  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id
  end
  def new
    @article = Article.new
  end
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash.notice = "Article '#{@article.title}' is deleted forever!"
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
      @article = Article.find(params[:id])
      @article.update(article_params)

      flash.notice = "Article '#{@article.title}' Updated!"

      redirect_to article_path(@article)
  end

  def create
    @article = Article.new(article_params)
#      title: params[:article][:title],
#      body: params[:article][:body],
#     published:  params[:article][:published]
#        )
    @article.save
    flash.notice = "Article '#{@article.title}'is listed!"
    redirect_to article_path(@article)
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :tag_list, :published, :image)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    @comment.save

    redirect_to article_path(@comment.article)
  end

  def comment_params
    params.require(:comment).permit(:author_name, :body, :date)

  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
  @tags = Tag.all
  end

  def show
  @tag = Tag.find(params[:id])
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    flash.notice = "This tag has vanished forever!"
    redirect_to tags_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def article_params
      params.require(:article).permit(:title, :body, :published, :tag_list, :image)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
  <h4>The author of this comment is: <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %></p>
  <p class="comment"><%= comment.date %></p>
  <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> after the article has been published.</p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>

  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>

  <p>
    <%= f.label :published %><br />
    <%= f.check_box :published %>
  </p>
  <p>
    <% if @article.image.exists? %>
        <%= image_tag @article.image.url %><br/>
    <% end %>
    <%= f.label :image, "Attach a New Image" %><br />
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<%end%>

app/views/articles/edit.html.erb
<h1>Edit/Review an Article</h1>
<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>Blogged Super Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
       <%= link_to article.title, article_path(article) %>
    </li>
  <% end %>

</ul>

<%= link_to 'Create New Article Now!', new_article_path, class: "new_article" %>
<br>
<br>
<p><%= link_to "Check the tags we have for you >>", tags_path %></p>

app/views/articles/new.html.erb
<h1> Create a new post</h1>
<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>
<br>
<p><%= image_tag @article.image.url(:medium) %></p>
<br>
<h3>Comments on this post(<%= @article.comments.size %>)</h3>
<%= render partial: 'articles/comment', collection: @article.comments %>
<p>
  Your Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>

<%= link_to "edit", edit_article_path(@article) %>
<%= link_to "delete", article_path(@article),data: {confirm:"Do you want to delete this for real?"}, method: :delete %>
<%= render partial: 'comments/form' %>
<p><%= link_to "<< Back to Articles List", articles_path %></p>

app/views/comments/_form.html.erb
<h4>Post a Comment</h4>
<%= form_for [ @article, @comment ] do |f| %>
  <p>
    <%= f.label :author_name, "Your Name"  %>
    <%= f.text_field :author_name,placeholder: "Type your name here" %>
  </p>
  <p>
    <%= f.label :body, "Your comments go here..." %><br/>
    <%= f.text_area :body, placeholder: "Here you make your text" %>
  </p>
  <p>
    <p>
      <%= f.label :date, "Your birthdate"%><br/>
      <%= f.date_field :date, placeholder: "dd/mm/yyyy" %>
    </p>
    <p>
    <br>
    <%= f.submit 'Submit' %>
  </p>
<% end %>
<p></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="flash"><%= flash.notice %></p>
<%= yield %>

</body>
</html>

app/views/tags/index.html.erb
<h1>Your tags so far are...</h1>

<ul id="tags">
  <% @tags.each do |tag| %>
    <li>
       <%= link_to tag.name, tag_path(tag.id) %>
       <%= link_to "Erase", tag_path(tag.id),data: {confirm:"This will be gone for good,ok?"}, method: :delete %>
    </li>
  <% end %>
  <li>
    <br>
    <br>
    <p><%= link_to "<< Back to Articles List", articles_path %></p>
  </li
</ul>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
  <br>
  <br>
  <p><%= link_to "Check the tags we have for you >>", tags_path %></p>
</ul>